"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class AdminReportTimePeriod(str, Enum):
    r"""A time period for the admin report."""
    WEEK = 'WEEK'
    MONTH = 'MONTH'
    YEAR = 'YEAR'
