"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import dto_clusters_dbfsstorageinfodto as shared_dto_clusters_dbfsstorageinfodto
from ..shared import dto_clusters_s3storageinfodto as shared_dto_clusters_s3storageinfodto
from dataclasses_json import Undefined, dataclass_json
from songbird import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class DTOClustersClusterLogConfDTO:
    dbfs: Optional[shared_dto_clusters_dbfsstorageinfodto.DTOClustersDbfsStorageInfoDTO] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dbfs'), 'exclude': lambda f: f is None }})
    s3: Optional[shared_dto_clusters_s3storageinfodto.DTOClustersS3StorageInfoDTO] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('s3'), 'exclude': lambda f: f is None }})
    

