"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .dto_clusters_dbfsstorageinfodto import DTOClustersDbfsStorageInfoDTO
from .dto_clusters_s3storageinfodto import DTOClustersS3StorageInfoDTO
from dataclasses_json import Undefined, dataclass_json
from songbird import utils
from typing import Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class DTOClustersClusterLogConfDTO:
    dbfs: Optional[DTOClustersDbfsStorageInfoDTO] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('dbfs'), 'exclude': lambda f: f is None }})
    s3: Optional[DTOClustersS3StorageInfoDTO] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('s3'), 'exclude': lambda f: f is None }})
    

