"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from .columnschema import ColumnSchema
from .metricschema import MetricSchema
from .schemametadata import SchemaMetadata
from dataclasses_json import Undefined, dataclass_json
from songbird import utils
from typing import Dict, Optional


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class EntitySchema:
    r"""Entity schema for a dataset"""
    columns: Dict[str, ColumnSchema] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('columns') }})
    r"""Column schema for a given column"""
    metadata: Optional[SchemaMetadata] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metadata'), 'exclude': lambda f: f is None }})
    metrics: Optional[Dict[str, MetricSchema]] = dataclasses.field(default=None, metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metrics') }})
    r"""Schema for user-defined metrics (map of unique custom metric labels to their definitions)"""
    

