"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import awsmarketplacemetadata as shared_awsmarketplacemetadata
from dataclasses_json import Undefined, dataclass_json
from songbird import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class GetMarketplaceMetadataResponse:
    r"""Response for listing organization"""
    metadata: shared_awsmarketplacemetadata.AWSMarketplaceMetadata = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('metadata') }})
    

