"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import dto_jobs_jobdto as shared_dto_jobs_jobdto
from dataclasses_json import Undefined, dataclass_json
from songbird import utils


@dataclass_json(undefined=Undefined.EXCLUDE)

@dataclasses.dataclass
class ListJobsResponse:
    r"""ListJobs default response"""
    jobs: list[shared_dto_jobs_jobdto.DTOJobsJobDTO] = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('jobs') }})
    

