"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
from ..shared import databricksconnection as shared_databricksconnection
from dataclasses_json import Undefined, dataclass_json
from songbird import utils


@dataclass_json(undefined=Undefined.EXCLUDE)
@dataclasses.dataclass
class RefreshConnectionByOrgIDResponse:
    r"""RefreshConnection default response"""
    
    connection: shared_databricksconnection.DatabricksConnection = dataclasses.field(metadata={'dataclasses_json': { 'letter_case': utils.get_field_name('connection') }})
    