"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum

class SubscriptionTier(str, Enum):
    FREE = 'FREE'
    PAID = 'PAID'
    AWS_MARKETPLACE = 'AWS_MARKETPLACE'
    SUBSCRIPTION = 'SUBSCRIPTION'
