"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import response as shared_response
from ...models.shared import transactioncommitrequest as shared_transactioncommitrequest
from typing import Optional


@dataclasses.dataclass
class CommitTransactionRequest:
    transaction_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'transaction_id', 'style': 'form', 'explode': True }})
    transaction_commit_request: shared_transactioncommitrequest.TransactionCommitRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    



@dataclasses.dataclass
class CommitTransactionResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    response: Optional[shared_response.Response] = dataclasses.field(default=None)
    r"""CommitTransaction default response"""
    

