"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from typing import Optional



@dataclasses.dataclass
class DeleteReferenceProfileRequest:
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model_id', 'style': 'simple', 'explode': False }})
    r"""The unique model ID in your company."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    reference_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'reference_id', 'style': 'simple', 'explode': False }})
    r"""Unique reference Id."""
    




@dataclasses.dataclass
class DeleteReferenceProfileResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    delete_reference_profile_default_application_json_boolean: Optional[bool] = dataclasses.field(default=None)
    r"""true if successful, false if we encounter failures"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

