"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import adminreportresponse as shared_adminreportresponse
from typing import Final, Optional



@dataclasses.dataclass
class GenerateReportRequest:
    REPORT_TYPE: Final[str] = dataclasses.field(default='SESSIONS', metadata={'query_param': { 'field_name': 'report_type', 'style': 'form', 'explode': True }})
    




@dataclasses.dataclass
class GenerateReportResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    admin_report_response: Optional[shared_adminreportresponse.AdminReportResponse] = dataclasses.field(default=None)
    r"""GenerateReport default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

