"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import getaccountmembershipsresponse as shared_getaccountmembershipsresponse
from ..shared import role as shared_role
from typing import Optional


@dataclasses.dataclass
class GetAccountMembershipsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    managed_org_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'managed_org_id', 'style': 'form', 'explode': True }})
    role: Optional[shared_role.Role] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'role', 'style': 'form', 'explode': True }})
    user_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'user_id', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class GetAccountMembershipsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    get_account_memberships_response: Optional[shared_getaccountmembershipsresponse.GetAccountMembershipsResponse] = dataclasses.field(default=None)
    r"""GetAccountMemberships default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

