"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import getdefaultmembershipresponse as shared_getdefaultmembershipresponse
from typing import Optional


@dataclasses.dataclass
class GetDefaultMembershipForEmailSecurity:
    
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    

@dataclasses.dataclass
class GetDefaultMembershipForEmailRequest:
    
    email: str = dataclasses.field(metadata={'query_param': { 'field_name': 'email', 'style': 'form', 'explode': True }})
    

@dataclasses.dataclass
class GetDefaultMembershipForEmailResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_default_membership_response: Optional[shared_getdefaultmembershipresponse.GetDefaultMembershipResponse] = dataclasses.field(default=None)
    r"""GetDefaultMembershipForEmail default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    