"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import columnschema as shared_columnschema
from typing import Optional



@dataclasses.dataclass
class GetEntitySchemaColumnSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class GetEntitySchemaColumnRequest:
    column_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'column_id', 'style': 'simple', 'explode': False }})
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class GetEntitySchemaColumnResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    column_schema: Optional[shared_columnschema.ColumnSchema] = dataclasses.field(default=None)
    r"""GetEntitySchemaColumn default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

