"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import notificationaction as shared_notificationaction
from typing import Optional



@dataclasses.dataclass
class GetNotificationActionSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class GetNotificationActionRequest:
    action_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'action_id', 'style': 'simple', 'explode': False }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class GetNotificationActionResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    notification_action: Optional[shared_notificationaction.NotificationAction] = dataclasses.field(default=None)
    r"""GetNotificationAction default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

