"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import organizationmetadata as shared_organizationmetadata
from typing import Optional


@dataclasses.dataclass
class GetOrganizationSecurity:
    
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    

@dataclasses.dataclass
class GetOrganizationRequest:
    
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""The unique ID of an organization"""
    

@dataclasses.dataclass
class GetOrganizationResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    organization_metadata: Optional[shared_organizationmetadata.OrganizationMetadata] = dataclasses.field(default=None)
    r"""The organization metadata"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    