"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import subscriptionsummary as shared_subscriptionsummary
from typing import List, Optional


@dataclasses.dataclass
class GetOrganizationSubscriptionsRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetOrganizationSubscriptionsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    classes: Optional[List[shared_subscriptionsummary.SubscriptionSummary]] = dataclasses.field(default=None)
    r"""GetOrganizationSubscriptions default response"""
    

