"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import getaccountmembershipsresponse as shared_getaccountmembershipsresponse
from typing import Optional



@dataclasses.dataclass
class GetOrgRoleMembershipsSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class GetOrgRoleMembershipsRequest:
    managed_org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'managed_org_id', 'style': 'simple', 'explode': False }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    role: str = dataclasses.field(metadata={'path_param': { 'field_name': 'role', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class GetOrgRoleMembershipsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_account_memberships_response: Optional[shared_getaccountmembershipsresponse.GetAccountMembershipsResponse] = dataclasses.field(default=None)
    r"""GetOrgRoleMemberships default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

