"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import getprofileobservatorylinkrequest as shared_getprofileobservatorylinkrequest
from ...models.shared import getprofileobservatorylinkresponse as shared_getprofileobservatorylinkresponse
from typing import Optional


@dataclasses.dataclass
class GetProfileObservatoryLinkRequest:
    dataset_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'dataset_id', 'style': 'simple', 'explode': False }})
    get_profile_observatory_link_request: shared_getprofileobservatorylinkrequest.GetProfileObservatoryLinkRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class GetProfileObservatoryLinkResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    get_profile_observatory_link_response: Optional[shared_getprofileobservatorylinkresponse.GetProfileObservatoryLinkResponse] = dataclasses.field(default=None)
    r"""GetProfileObservatoryLink default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

