"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import pagerdutynotificationaction as shared_pagerdutynotificationaction
from typing import Optional



@dataclasses.dataclass
class GetPagerDutyNotificationActionPayloadResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    pager_duty_notification_action: Optional[shared_pagerdutynotificationaction.PagerDutyNotificationAction] = dataclasses.field(default=None)
    r"""getPagerDutyNotificationActionPayload default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

