"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import referenceprofileitemresponse as shared_referenceprofileitemresponse
from typing import Optional



@dataclasses.dataclass
class GetReferenceProfileRequest:
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model_id', 'style': 'simple', 'explode': False }})
    r"""The unique model ID in your company."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    reference_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'reference_id', 'style': 'simple', 'explode': False }})
    r"""Unique reference Id."""
    




@dataclasses.dataclass
class GetReferenceProfileResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    reference_profile_item_response: Optional[shared_referenceprofileitemresponse.ReferenceProfileItemResponse] = dataclasses.field(default=None)
    r"""The metadata for the summarized dataset profile including paths to JSON and protobuf data"""
    

