"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import slacknotificationaction as shared_slacknotificationaction
from typing import Optional



@dataclasses.dataclass
class GetSlackNotificationActionPayloadSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class GetSlackNotificationActionPayloadResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    slack_notification_action: Optional[shared_slacknotificationaction.SlackNotificationAction] = dataclasses.field(default=None)
    r"""getSlackNotificationActionPayload default response"""
    

