"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import getprofileobservatorylinkrequest as shared_getprofileobservatorylinkrequest
from ..shared import getprofileobservatorylinkresponse as shared_getprofileobservatorylinkresponse
from typing import Optional



@dataclasses.dataclass
class GetSessionProfileObservatoryLinkRequest:
    get_profile_observatory_link_request: shared_getprofileobservatorylinkrequest.GetProfileObservatoryLinkRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    session_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'session_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class GetSessionProfileObservatoryLinkResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    get_profile_observatory_link_response: Optional[shared_getprofileobservatorylinkresponse.GetProfileObservatoryLinkResponse] = dataclasses.field(default=None)
    r"""GetSessionProfileObservatoryLink default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

