"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import accountuser as shared_accountuser
from typing import Optional



@dataclasses.dataclass
class ListAccountUsersSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class ListAccountUsersRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    




@dataclasses.dataclass
class ListAccountUsersResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    account_users: Optional[list[shared_accountuser.AccountUser]] = dataclasses.field(default=None)
    r"""ListAccountUsers default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    

