"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import listuserapikeys as shared_listuserapikeys
from typing import Optional


@dataclasses.dataclass
class ListAPIKeysRequest:
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    user_id: Optional[str] = dataclasses.field(default=None, metadata={'query_param': { 'field_name': 'user_id', 'style': 'form', 'explode': True }})
    r"""The unique user ID in an organization.
     A list of objects with key ID and other metadata about the keys, but no secret values
    """
    



@dataclasses.dataclass
class ListAPIKeysResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    list_user_api_keys: Optional[shared_listuserapikeys.ListUserAPIKeys] = dataclasses.field(default=None)
    r"""A list of objects with key ID and other metadata about the keys, but no secret values"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

