"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import listjobsresponse as shared_listjobsresponse
from typing import Optional


@dataclasses.dataclass
class ListJobsSecurity:
    
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    

@dataclasses.dataclass
class ListJobsResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    list_jobs_response: Optional[shared_listjobsresponse.ListJobsResponse] = dataclasses.field(default=None)
    r"""ListJobs default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    