"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import segmentlistresponse as shared_segmentlistresponse
from typing import Optional



@dataclasses.dataclass
class ListSegmentsRequest:
    model_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'model_id', 'style': 'simple', 'explode': False }})
    r"""The unique model ID in your company."""
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    r"""Your company's unique organization ID"""
    




@dataclasses.dataclass
class ListSegmentsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    segment_list_response: Optional[shared_segmentlistresponse.SegmentListResponse] = dataclasses.field(default=None)
    r"""The list of segments for the dataset profile"""
    

