"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import patchaccountmembershipsrequest as shared_patchaccountmembershipsrequest
from ..shared import response as shared_response
from ..shared import role as shared_role
from typing import Optional



@dataclasses.dataclass
class PatchOrganizationMembershipsSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class PatchOrganizationMembershipsRequest:
    managed_org_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'managed_org_id', 'style': 'form', 'explode': True }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    patch_account_memberships_request: shared_patchaccountmembershipsrequest.PatchAccountMembershipsRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    role: shared_role.Role = dataclasses.field(metadata={'query_param': { 'field_name': 'role', 'style': 'form', 'explode': True }})
    




@dataclasses.dataclass
class PatchOrganizationMembershipsResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    response: Optional[shared_response.Response] = dataclasses.field(default=None)
    r"""PatchOrganizationMemberships default response"""
    

