"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import void as shared_void
from typing import Optional



@dataclasses.dataclass
class PostMonitorConfigValidationJobSecurity:
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    




@dataclasses.dataclass
class PostMonitorConfigValidationJobResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    void: Optional[shared_void.Void] = dataclasses.field(default=None)
    r"""PostMonitorConfigValidationJob default response"""
    

