"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import void as shared_void
from typing import Optional


@dataclasses.dataclass
class PostSpansRawRequest:
    request_body: bytes = dataclasses.field(metadata={'request': { 'media_type': 'application/x-protobuf' }})
    x_whylabs_resource: str = dataclasses.field(metadata={'header': { 'field_name': 'X-WHYLABS-RESOURCE', 'style': 'simple', 'explode': False }})
    



@dataclasses.dataclass
class PostSpansRawResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    void: Optional[shared_void.Void] = dataclasses.field(default=None)
    r"""PostSpans default response"""
    

