"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import provisionnewawsmarketplaceuserresponse as shared_provisionnewawsmarketplaceuserresponse
from typing import Optional


@dataclasses.dataclass
class ProvisionAWSMarketplaceNewUserSecurity:
    
    api_key_auth: str = dataclasses.field(metadata={'security': { 'scheme': True, 'type': 'apiKey', 'sub_type': 'header', 'field_name': 'X-API-Key' }})
    

@dataclasses.dataclass
class ProvisionAWSMarketplaceNewUserResponse:
    
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    provision_new_aws_marketplace_user_response: Optional[shared_provisionnewawsmarketplaceuserresponse.ProvisionNewAWSMarketplaceUserResponse] = dataclasses.field(default=None)
    r"""ProvisionAWSMarketplaceNewUser default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    