"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import provisionnewuserresponse as shared_provisionnewuserresponse
from typing import Optional



@dataclasses.dataclass
class ProvisionNewUserResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    provision_new_user_response: Optional[shared_provisionnewuserresponse.ProvisionNewUserResponse] = dataclasses.field(default=None)
    r"""ProvisionNewUser default response"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    

