"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import putaccountmembershipsrequest as shared_putaccountmembershipsrequest
from ..shared import role as shared_role
from ..shared import statusresponse as shared_statusresponse
from typing import Optional


@dataclasses.dataclass
class PutOrganizationMembershipsRequest:
    managed_org_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'managed_org_id', 'style': 'form', 'explode': True }})
    org_id: str = dataclasses.field(metadata={'path_param': { 'field_name': 'org_id', 'style': 'simple', 'explode': False }})
    put_account_memberships_request: shared_putaccountmembershipsrequest.PutAccountMembershipsRequest = dataclasses.field(metadata={'request': { 'media_type': 'application/json' }})
    role: shared_role.Role = dataclasses.field(metadata={'query_param': { 'field_name': 'role', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class PutOrganizationMembershipsResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_response: Optional[shared_statusresponse.StatusResponse] = dataclasses.field(default=None)
    r"""PutOrganizationMemberships default response"""
    

