"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ..shared import registerdatabricksconnectionresponse as shared_registerdatabricksconnectionresponse
from typing import Optional



@dataclasses.dataclass
class RegisterDatabricksConnectionResponse:
    content_type: str = dataclasses.field()
    status_code: int = dataclasses.field()
    raw_response: Optional[requests_http.Response] = dataclasses.field(default=None)
    register_databricks_connection_response: Optional[shared_registerdatabricksconnectionresponse.RegisterDatabricksConnectionResponse] = dataclasses.field(default=None)
    r"""RegisterDatabricksConnection default response"""
    

