"""Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT."""

from __future__ import annotations
import dataclasses
import requests as requests_http
from ...models.shared import transactionstatusresponse as shared_transactionstatusresponse
from typing import Optional


@dataclasses.dataclass
class TransactionStatusRequest:
    transaction_id: str = dataclasses.field(metadata={'query_param': { 'field_name': 'transaction_id', 'style': 'form', 'explode': True }})
    



@dataclasses.dataclass
class TransactionStatusResponse:
    content_type: str = dataclasses.field()
    r"""HTTP response content type for this operation"""
    raw_response: requests_http.Response = dataclasses.field()
    r"""Raw HTTP response; suitable for custom response parsing"""
    status_code: int = dataclasses.field()
    r"""HTTP response status code for this operation"""
    transaction_status_response: Optional[shared_transactionstatusresponse.TransactionStatusResponse] = dataclasses.field(default=None)
    r"""TransactionStatus default response"""
    

